### ISSUE TITLE
pre-trained model

### ISSUE THREAD

**Issue by javierztl** [DylanAuty/ObjCAViT#3]
Thank you for your excellent work. Can you please release some pre-trained ckpt for a demo?

**Comment by DylanAuty** [comment]
Hello, apologies for the delay and thank you for your patience! We have now released the best NYU model [here](https://github.com/DylanAuty/ObjCAViT/releases/tag/nyu_graphbins_enet-b5_ocv_pos_learned_bbox_wh_emb_128_old_dl_1).
